import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/libs/appwrite/types`.

export enum Direction {
    CREDIT = "credit",
    DEBIT = "debit"
}

export enum ActivePlan {
    FREE = "free",
    PRO = "pro",
    PLUS = "plus"
}

export enum ActivePlanPeriod {
    YEARLY = "yearly",
    MONTHLY = "monthly"
}

export type Category = Models.Row & {
    title: string;
    enabled: boolean;
    templates: Template[];
    icon: string | null;
}

export type Template = Models.Row & {
    category: Category;
    title: string | null;
    prompt: string;
    previewFileId: string | null;
    function: string;
}

export type Creation = Models.Row & {
    executions: CreationExecution[];
    originalFileId: string;
    outputFileId: string | null;
    status: 'pending' | 'processing' | 'completed' | 'error';
    templateId?: string | null;
    categoryId?: string | null;
    template?: Template;
}

export type CreationExecution = Models.Row & {
    creation: Creation;
}

export type SupportRequests = Models.Row & {
    category: string;
    email: string | null;
    message: string;
    notify_user: boolean;
}

export type Feedbacks = Models.Row & {
    rating: number;
    message: string | null;
    table_name: string | null;
    table_id: string | null;
    email: string | null;
    user_id: string | null;
}

export type Balances = Models.Row & {
    userId: string;
    balance: number;
    lifetime_balance_granted: number;
    lifetime_balance_spent: number;
    last_balance_updated_at: string | null;
    version: number;
    histories: BalanceHistory[];
}

export type BalanceHistory = Models.Row & {
    balance: Balances;
    direction: Direction;
    amount: number;
    balance_before: number;
    balance_after: number;
}

export type StripeCustomers = Models.Row & {
    userId: string;
    stripeCustomerId: string;
}

export type UserSubscriptions = Models.Row & {
    stripeCustomerId: string;
    provider: string;
    planId: string;
    status: string;
    currentPeriodStart: string;
    currentPeriodEnd: string;
    subscriptionId: string;
    metadata: string | null;
}

export type PaymentTransactions = Models.Row & {
    stripeCustomerId: string;
    provider: string;
    type: string;
    amount: number;
    currency: string;
    planId: string | null;
    credits: number | null;
    status: string;
    paymentIntentId: string;
    metadata: string | null;
}

export type CreditTransactions = Models.Row & {
    userId: string;
    type: string;
    amount: number;
    balance: number;
    description: string;
    relatedTransactionId: string | null;
    metadata: string | null;
}

export type UserCreditBalances = Models.Row & {
    userId: string;
    balance: number;
    totalEarned: number;
    totalSpent: number;
}

export type Customers = Models.Row & {
    active_plan: ActivePlan;
    active_plan_period: ActivePlanPeriod;
}
